### ISSUE TITLE
Getting "Headers is not defined" when using this starter

### ISSUE THREAD

**Issue by bpulito** [domeccleston/langchain-ts-starter#2]
Tried to use the starter but get the following error when running npm start:

$ npm start

> langchain-ts-starter@1.0.0 start
> tsx -r dotenv/config src/index.ts

ReferenceError: Headers is not defined
    at createRequest (file:///Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/langchain/src/util/axios-fetch-adapter.js:273:19)
    at fetchAdapter (file:///Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/langchain/src/util/axios-fetch-adapter.js:196:19)
    at dispatchRequest (/Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/openai/dist/common.js:149:22
    at /Users/brian_pulitous.ibm.com/git/langchain-ts-starter/node_modules/openai/dist/api.js:1738:133

Any ideas what might be going run?

**Comment by bpulito** [comment]
I figured it out. I was running an old version of Node.js
