### ISSUE TITLE
When I run 'npm start', it prints 'Headers is not defined'. I can run 'npx turbo run build lint format' successfully.

### ISSUE THREAD

**Issue by Clifforid** [domeccleston/langchain-ts-starter#9]
ReferenceError: Headers is not defined
    at createRequest (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/langchain/src/util/axios-fetch-adapter.js:273:19)
    at fetchAdapter (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/langchain/src/util/axios-fetch-adapter.js:196:19)
    at dispatchRequest (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/axios/lib/helpers/bind.js:9:15)
    at <anonymous> (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/openai/dist/common.js:149:22)
    at <anonymous> (/Users/zhangchaoqun/Developer/study/langchain/langchain-ts-starter/node_modules/openai/dist/api.js:1740:133)

**Comment by manjeshpv** [comment]
getting same issue
